name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: tdolby/experimental:ace-minimal-13.0.4.0-alpine
      env:
        LICENSE: accept

    steps:
      - uses: actions/checkout@v4

      - name: Build the application and test it
        shell: bash
        run: |
          export LICENSE=accept
          set +e
          . /opt/ibm/ace-13/server/bin/mqsiprofile
          set -e

          echo "Building application"
          ibmint package --input-path . \
            --output-bar-file $PWD/tea-application-combined.bar \
            --project TeaSharedLibraryJava \
            --project TeaSharedLibrary \
            --project TeaRESTApplication \
            --project TeaCallableApplicationV2 \
            --compile-maps-and-schemas

      - name: Upload BAR file
        uses: actions/upload-artifact@v4
        with:
          name: bar-file
          path: tea-application-combined.bar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download BAR file
        uses: actions/download-artifact@v4
        with:
          name: bar-file

      - name: Deploy to ACEaaS
        env:
          ACE_SERVER_URL: ${{ secrets.ACE_SERVER_URL }}
          ACE_API_KEY: ${{ secrets.ACE_API_KEY }}
        run: |
          echo "Deploying to ACEaaS"
          curl -X POST "$ACE_SERVER_URL/apis/integration-servers/ir-03-medium/deployments" \
            -H "Authorization: Bearer $ACE_API_KEY" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @tea-application-combined.bar
