# CI build to validate PR changes before merging

name: CI_Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Disable temporarily during workflow development
  #push:
  #  branches: [ main, minikube-cp4i ]
  #pull_request:
  #  branches: [ main, minikube-cp4i ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: tdolby/experimental:ace-minimal-13.0.4.0-alpine
      env:
        LICENSE: accept
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Install curl
        run: apk update && apk add curl
          
      - name: Build the application and test it
        shell: bash
        run: |
          echo "Loading ACE profile"
          export LICENSE=accept
          set +e # Don't fail on error if the profile has already been loaded
          . /opt/ibm/ace-13/server/bin/mqsiprofile
          set -e # Fail on error - this must be done after the profile in case the container has the profile loaded already

          echo ========================================================================
          echo Building application
          echo ========================================================================
          # Using --compile-maps-and-schemas for 13.0.1 and later . . . 
          ibmint package --input-path . --output-bar-file $PWD/tea-application-combined.bar --project TeaSharedLibraryJava --project TeaSharedLibrary --project TeaRESTApplication --project TeaCallableApplicationV2 --compile-maps-and-schemas 

          echo ========================================================================
          echo Building unit tests
          echo ========================================================================
          # Create the unit test work directory
          mqsicreateworkdir /tmp/test-work-dir
          mqsibar -w /tmp/test-work-dir -a $PWD/tea-application-combined.bar 
          # Build just the unit tests
          ibmint deploy --input-path . --output-work-directory /tmp/test-work-dir --project TeaRESTApplication_UnitTest

          echo ========================================================================
          echo Running unit tests
          echo ========================================================================
          IntegrationServer -w /tmp/test-work-dir --no-nodejs --start-msgflows false --test-project TeaRESTApplication_UnitTest --test-junit-options --reports-dir=junit-reports
      
      - name: Deploy to ACEaaS
        env:
          ACE_SERVER_URL: ${{ secrets.ACE_SERVER_URL }}
          ACE_API_KEY: ${{ secrets.ACE_API_KEY }}
        run: |
          echo "Deploying to ACEaaS"
          curl -X POST "$ACE_SERVER_URL/apis/integration-servers/MyServer/deployments" \
            -H "Authorization: Bearer $ACE_API_KEY" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @$PWD/tea-application-combined.bar
