name: CI_Octopus_Integration

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build & test inside ACE container with LICENSE=accept
      - name: Build BAR inside ACE container
        run: |
          docker run --rm \
            -e LICENSE=accept \
            -v $GITHUB_WORKSPACE:/workspace \
            -w /workspace \
            tdolby/experimental:ace-minimal-13.0.4.0-alpine \
            bash -c "
              . /opt/ibm/ace-13/server/bin/mqsiprofile && \
              ibmint package \
                --input-path . \
                --output-bar-file tea-application-combined.bar \
                --project TeaSharedLibraryJava \
                --project TeaSharedLibrary \
                --project TeaRESTApplication \
                --project TeaCallableApplicationV2 \
                --compile-maps-and-schemas
            "

      # Install zip utility to package BAR
      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      # Prepare ZIP file for Octopus
      - name: Prepare BAR file for Octopus
        run: |
          VERSION=1.0.${{ github.run_number }}
          cp ./tea-application-combined.bar ./TeaApplication.${VERSION}.bar
          zip TeaApplication.${VERSION}.zip TeaApplication.${VERSION}.bar

      # Push ZIP package to Octopus Deploy
      - name: Push ZIP package to Octopus Deploy
        uses: OctopusDeploy/push-package-action@v3
        with:
          api_key: ${{ secrets.OCTOPUS_API_KEY }}
          server: ${{ secrets.OCTOPUS_SERVER_URL }}
          space: 'Default'
          packages: ./TeaApplication.1.0.${{ github.run_number }}.zip
